# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 14:47
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_auto_20180126_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['address'], 'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name'], 'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['description'], 'verbose_name': 'Atributo', 'verbose_name_plural': 'Atributos'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'verbose_name': 'Observação', 'verbose_name_plural': 'Observações'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Proprietário', 'verbose_name_plural': 'Proprietários'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Telefone', 'verbose_name_plural': 'Telefones'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
        migrations.AlterField(
            model_name='build',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='build',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='build',
            name='availability',
            field=models.BooleanField(choices=[(True, 'à venda'), (False, 'vendido')], default=True, verbose_name='disponibilidade'),
        ),
        migrations.AlterField(
            model_name='build',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='banheiros'),
        ),
        migrations.AlterField(
            model_name='build',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='quartos'),
        ),
        migrations.AlterField(
            model_name='build',
            name='building_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='build',
            name='condominium_fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='BRL', max_digits=8, verbose_name='taxa de condomínio'),
        ),
        migrations.AlterField(
            model_name='build',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.District', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='build',
            name='empty',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='vago'),
        ),
        migrations.AlterField(
            model_name='build',
            name='features',
            field=models.ManyToManyField(blank=True, to='imoveis.Feature', verbose_name='Atributos'),
        ),
        migrations.AlterField(
            model_name='build',
            name='janitor_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='zelador'),
        ),
        migrations.AlterField(
            model_name='build',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, to='imoveis.Owner', verbose_name='Proprietários'),
        ),
        migrations.AlterField(
            model_name='build',
            name='parking_slots',
            field=models.PositiveIntegerField(default=0, verbose_name='vagas na garagem'),
        ),
        migrations.AlterField(
            model_name='build',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='imoveis.Picture', verbose_name='Figuras'),
        ),
        migrations.AlterField(
            model_name='build',
            name='project',
            field=models.CharField(blank=True, max_length=200, verbose_name='empreendimento'),
        ),
        migrations.AlterField(
            model_name='build',
            name='selling_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='BRL', max_digits=15, verbose_name='valor de venda'),
        ),
        migrations.AlterField(
            model_name='build',
            name='square_meters',
            field=models.PositiveIntegerField(default=0, verbose_name='metragem'),
        ),
        migrations.AlterField(
            model_name='build',
            name='suites',
            field=models.PositiveIntegerField(default=0, verbose_name='suites'),
        ),
        migrations.AlterField(
            model_name='build',
            name='tower',
            field=models.CharField(blank=True, max_length=200, verbose_name='torre'),
        ),
        migrations.AlterField(
            model_name='build',
            name='unit',
            field=models.PositiveIntegerField(default=0, verbose_name='unidade'),
        ),
        migrations.AlterField(
            model_name='build',
            name='units_per_floor',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='unidades/andar'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=500, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.CharField(max_length=200, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='description',
            field=models.CharField(max_length=500, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='country',
            field=models.CharField(blank=True, default='+55', max_length=6, validators=[django.core.validators.RegexValidator(message='Um código de país pode ou não começar com um sinal demais(+) e deve conter até 6 valores. Um valor pode ser umdígito(0-9), um ponto(.) ou um hífen(-).', regex='^\\+[\\d\\-\\.]{1,6}$')], verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Um número de telefone deve conter de 8 a 9 dígitos(0-9).', regex='\\d{8,9}$')], verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='state',
            field=models.CharField(default='011', max_length=3, validators=[django.core.validators.RegexValidator(message='Um código de região deve conter até 3 dígitos(0-9).', regex='\\d{2,3}$')], verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
    ]
